version: 2.1
jobs:
  build:
    resource_class: large
    docker:
      # image with node, npm and yarn installed
      - image: cimg/node:14.17.5
    steps:
      # checkout workspace to repo code
      - checkout

      # restore workspace if available
      # to skip re-installing node_modules
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      # install dependencies
      - run: yarn --ignore-engines --network-concurrency=1

      # save node_modules to cache
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # build code to production file
      - run:
          name: yarn build according to branch
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              NODE_OPTIONS="--max_old_space_size=7168" REACT_APP_GA_MEASUREMENT_ID="G-XRDECDZHLR" yarn build --transpile-only
            else
              NODE_OPTIONS="--max_old_space_size=7168" yarn build --transpile-only
            fi

      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: cimg/node:14.17.5
    steps:
      - attach_workspace:
          at: .

      - restore_cache:
          keys:
            - v1-npm-global

      - run:
          name: install ipfs-deploy
          command: NPM_CONFIG_PREFIX=~/.npm-global npm install -g ipfs-deploy

      - run:
          name: install AWS CLI
          command: |
            sudo apt-get --allow-releaseinfo-change update
            sudo apt-get install awscli

      - save_cache:
          paths:
            - ~/.npm-global
          key: v1-npm-global

      - run:
          name: deploy to aws
          command: |
            if [ "${CIRCLE_BRANCH}" = "staging" ]; then
              aws s3 sync build s3://zilswap-ui-staging/ --delete
              aws cloudfront create-invalidation --distribution-id="E4QZBREBNL47S" --paths=/*
            elif [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync build s3://zilswap-ui/production --delete
              aws cloudfront create-invalidation --distribution-id="ESU80N8RF88HZ" --paths=/*
            elif [ "${CIRCLE_BRANCH}" = "develop" ]; then
              aws s3 sync build s3://zilswap-ui/develop --delete
              aws cloudfront create-invalidation --distribution-id="E2E0YSY2VDFHFV" --paths=/*
            fi

      - run:
          name: deploy to ipfs
          command: |
            if [ "${CIRCLE_BRANCH}" = "staging" ]; then
              IPFS_DEPLOY_CLOUDFLARE__ZONE=zilswap.exchange \
              IPFS_DEPLOY_CLOUDFLARE__RECORD=_dnslink.staging.zilswap.exchange \
              ~/.npm-global/bin/ipfs-deploy build/ -d cloudflare -C
            elif [ "${CIRCLE_BRANCH}" = "master" ]; then
              IPFS_DEPLOY_CLOUDFLARE__ZONE=zilswap.exchange \
              IPFS_DEPLOY_CLOUDFLARE__RECORD=_dnslink.zilswap.exchange \
              ~/.npm-global/bin/ipfs-deploy build/ -d cloudflare -C
            fi

workflows:
  build-and-deploy:
    jobs:
      - build:
          context: org-switcheo
          filters:
            branches:
              only:
                - master
                - staging
                - develop
      - deploy:
          context: org-switcheo
          requires:
            - build
